In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(a[:, 2])

[3 6 9]


In [4]:
a[0]

array([1, 2, 3])

In [5]:
print(a[:, 1])

[2 5 8]


In [6]:
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

# sélectionne la deuxième matrice
a[1]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [7]:
# On souhaite avoir 14 24 34 
x, y, z = a[:, 1, 1]

print(x, y, z)

14 24 34


In [8]:
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

a.sum(0)

array([[60, 63, 66],
       [69, 72, 75],
       [78, 81, 84]])

In [9]:
a*2

array([[[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[40, 42, 44],
        [46, 48, 50],
        [52, 54, 56]],

       [[60, 62, 64],
        [66, 68, 70],
        [72, 74, 76]]])

In [10]:
# 01 Exercice

In [11]:
x1 = np.array([[9, 1, 2],
       [8, 0, 2],
       [5, 1, 5]])

In [19]:
print( x1[0] )
print( x1[1] )
print( x1[2] )

[9 1 2]
[8 0 2]
[5 1 5]


In [20]:
# La deuxième colonne
print( x1[:, 1] )

# La première colonne
print( x1[:, 0] )

# La dernière colonne
print( x1[:, 1] )

[1 0 1]
[9 8 5]
[1 0 1]


In [26]:
"""
9 1 
8 0
"""
print( x1[:2,:2] )

[[9 1]
 [8 0]]


In [27]:
"""
0 2
1 5
"""
# start:end:step
print(x1[1:,1:])

[[0 2]
 [1 5]]


In [30]:
# Somme des lignes
x1.sum(1)

array([12, 10, 11])

In [32]:
# Somme des colonnes
x1.sum(0)

array([22,  2,  9])

In [35]:
# Somme des colonnes
x, y, z = x1.sum(0)
print(x, y, z)

# Somme des lignes
a, b, c = x1.sum(1)

print(a, b, c)

22 2 9
12 10 11


In [38]:
# 02 Exercice
x2 = np.array([ 
    [ [8, 4],[8, 9] ],
    [ [3, 0],[5, 0] ] 
])

print(x2)

[[[8 4]
  [8 9]]

 [[3 0]
  [5 0]]]


In [66]:
"""
8
8
"""

print( x2[0][:, 0] )

[8 8]


In [68]:
"""
4
9
"""

print( x2[0][:, 1] )

[4 9]


In [70]:
"""
0
0
"""

print( x2[1][:, 1] )

[0 0]


In [72]:
# 03 Exercice
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

print(a)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [75]:
"""
10 11 12
20 21 22
30 31 32
"""

# start:end:step
print( a[:,0] )

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [85]:
"""
14
24
34
"""
print(a)
# i:matrice, j:ligne, k:colonne
print(a[:,1:2,1:2])

# attention au dimension, plus simple à exploiter 
print(a[:, 1, 1])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]
[[[14]]

 [[24]]

 [[34]]]
[14 24 34]


In [88]:
print(a[:, 1, 2])

[15 25 35]


In [90]:
a = np.random.randint( 10, size = (10) )
# une promo - 20%
# On peut passer la matrice dans la fonction 
promo = lambda x : x * 0.8


In [92]:
print(a)
print(promo(a))

[3 5 7 3 0 2 0 7 6 0]
[2.4 4.  5.6 2.4 0.  1.6 0.  5.6 4.8 0. ]


In [94]:
a*1.2

array([3.6, 6. , 8.4, 3.6, 0. , 2.4, 0. , 8.4, 7.2, 0. ])

In [96]:
# Extraire les valeurs paires d'une matrice 
prices = np.array([82, 92, 89, 65, 77, 66, 69, 65, 79, 51])

In [99]:
mask= prices > 90

print(mask)

[False  True False False False False False False False False]


In [101]:
prices[mask]

array([92])

In [109]:
mask = (prices % 2 ) == 0

print(prices[mask])

[82 92 66]


In [113]:
# 04 Exercice

A = np.array([
    [13, 22, 28, 66, 40],
    [16, 59, 37, 33, 28],
    [34, 98, 54, 48, 96],
    [13, 84, 93, 79, 76],
    [63, 50, 10, 69, 12]
])

"""
A = np.array([
    [13, 22, 28, 66, 40],
    [16, 59, 37, 33, 28],
    [34, 98, 54, 48, 96],
    [13, 84, 93, 79, 76],
    [63, 50, 10, 69, 12]
])

Soit le tableau A suivant on cherche les valeurs minimales par ligne. (DANS LA DOC)

Nous aimerions à l'aide d'un script Python trouver tous les indices de tableau 
par ligne des minimaux et les enregistrer dans une liste de tuples comme dans l'exemple ci-dessous :

# Liste des minimaux et leur position sur chaque ligne
minTabLine = [(0, 13), (0, 16), (0, 34), (0, 13), (2, 10)]

"""

print('------')


------


In [156]:
"""
Une méthode est de regarder dans la documentation de Numpy si, on a une fonction qui travaille sur les tableaux.

Ou alors on utilise ses propres masks
"""
# 
minLine = np.amin(A, axis=1)
res = []
# Pour avoir les indices pour chaque ligne
for i, line in enumerate(A):
    # np.where donne l'indice de la valeur rechercher en fonction du mask 
    # print( np.where( A[i] == minLine[i] ) )
    j, =  np.where( A[i] == minLine[i] )
    
    res.append( (j[0],minLine[i]) )

print(res)

[(0, 13), (0, 16), (0, 34), (0, 13), (2, 10)]


In [141]:
np.array([0]).item(0)

0

In [157]:
## Pour Yves à travailler et comprendre pour la prochaine fois

minLine = np.amin(A, axis=1)
res = []
# Pour avoir les indices pour chaque ligne
for i, line in enumerate(A):
    # min par ligne
    m = minLine[i]
    # On cherche chaque min dans chaque ligne
    for k, j in enumerate(line):
        if j == m :
            res.append(((i, k), m))
print(res)   

[((0, 0), 13), ((1, 0), 16), ((2, 0), 34), ((3, 0), 13), ((4, 2), 10)]


In [163]:
# Exercice
"""
Utilisez un mask pour faire la recherche des valeurs supérieur à 10 et inférieur à 100

prices = np.array([ 43, 191, 108, 115, 104, 159, 113, 147,  46,   9,  17, 177,  27,
        10,  90,   6,  73, 188, 171, 154])
        
comptez le nombre de valeurs qui répondent à la recherche effectuée ci-dessus

"""


print('----')

----


In [166]:
prices = np.array([ 43, 191, 108, 115, 104, 159, 113, 147,  46,   9,  17, 177,  27,
        10,  90,   6,  73, 188, 171, 154])

# & en binaire obligatoire 
mask = (prices > 10) & (prices < 100 )

prices[mask]

# la somme du mask ==> la somme les True 
np.sum(mask)

6